### ISSUE TITLE
project looks great, but there are some build problems for me

### ISSUE THREAD

**Issue by firebrain7** [gradientpm/gvpm#1]
My platform : windows 10 pro
When I use camke to compile the project, there are some mistakes: 

CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: filesystem system thread) (found suitable
  version "1.71.0", minimum required is "1.47")

I have seen many pages on the internet, could you give me some advice?
(the details)
![Snipaste_2019-10-23_23-33-28](https://user-images.githubusercontent.com/16367644/67409778-9a856b00-f5ed-11e9-9e60-6fcd1a7006e7.png)

**Comment by songuke** [comment]
Hi, do you unzip Mitsuba dependencies on Windows? See this file: https://github.com/gradientpm/gvpm/blob/master/gradientdomain_dependencies_DEFAULT.zip

On Windows we used Scons build. On Linux it is CMake.

**Comment by firebrain7** [comment]
Thanks songuke. 
I have solved it by redirecting to the official dependencies folder when I use cmake  to build.
